ARG RANCHER_BASE_TAG=base
ARG RANCHER_REPO=rancher
FROM ${RANCHER_REPO}/rancher:${RANCHER_BASE_TAG}

ARG DAPPER_HOST_ARCH
ARG CATTLE_DASHBOARD_TAR_URL
ENV CATTLE_DASHBOARD_TAR_URL=$CATTLE_DASHBOARD_TAR_URL
# Specific version of OCI OCNE Driver
ARG OCI_OCNE_DRIVER_VERSION=v0.0.1
ARG OCI_OCNE_DRIVER_HASH=""
ENV OCI_OCNE_DRIVER_VERSION=$OCI_OCNE_DRIVER_VERSION
ENV OCI_OCNE_DRIVER_HASH=$OCI_OCNE_DRIVER_HASH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}
ENV K3S_ROOT_VERSION v0.11.0
ENV CATTLE_HELM_VERSION v2.16.8-rancher2
ENV CATTLE_MACHINE_VERSION v0.15.0-rancher98
ENV CATTLE_K3S_VERSION v1.25.5+k3s1
# version used by helm plugin install script
ENV CATTLE_HELM_UNITTEST_VERSION v0.1.7-rancher4
# helm 3 version
ENV HELM_VERSION v3.9.0
ENV KUSTOMIZE_VERSION v5.0.0
ENV GOPATH=/go PATH=/go/bin:/usr/local/go/bin:${PATH} SHELL=/bin/bash


# kontainer-driver-metadata branch to be set for specific branch other than dev/master, logic at rancher/rancher/pkg/settings/setting.go
ENV CATTLE_KDM_BRANCH=release-v2.7

# Update PATH to make sure git 2.27 is on the path
ENV PATH="/opt/rh/rh-git227/root/usr/bin:${PATH}" \
    KUSTOMIZE_URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_${ARCH}.tar.gz \
    YQ_URL=https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_${ARCH}

RUN curl -sLf ${KUSTOMIZE_URL} | tar -xzf - -C /usr/bin && \
    wget -O - ${YQ_URL} > /usr/bin/yq && chmod +x /usr/bin/yq && \
    chmod +x /usr/bin/kustomize


ENV HELM_HOME /root/.helm
ENV DAPPER_ENV REPO TAG DRONE_TAG DRONE_COMMIT DRONE_BRANCH DRONE_BUILD_EVENT SYSTEM_CHART_DEFAULT_BRANCH FOSSA_API_KEY GOGET_MODULE GOGET_VERSION RELEASE_ACTION RELEASE_TYPE POSTRELEASE_RANCHER_VERSION POSTRELEASE_RANCHER_STABLE
ENV DAPPER_SOURCE /go/src/github.com/rancher/rancher/
ENV DAPPER_OUTPUT ./bin ./dist ./go.mod ./go.sum ./pkg/apis/go.mod ./pkg/apis/go.sum ./pkg/client/go.mod ./pkg/client/go.sum ./scripts/package ./pkg/settings/setting.go ./package/Dockerfile ./Dockerfile.dapper
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_RUN_ARGS "-v rancher2-go16-pkg-1:/go/pkg -v rancher2-go16-cache-1:/root/.cache/go-build --privileged"
ENV GOCACHE /root/.cache/go-build
ENV HOME ${DAPPER_SOURCE}
VOLUME /var/lib/rancher
VOLUME /var/lib/kubelet
WORKDIR ${DAPPER_SOURCE}

# Set up the git 2.x environment variables so that it's on the path and the needed files on the LD_LIBRARY_PATH
RUN cat /etc/profile.d/git.sh >> /etc/profile

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
