FROM ghcr.io/oracle/oraclelinux:7-slim

RUN yum-config-manager --enable ol7_optional_latest && \
    yum-config-manager --enable ol7_addons && \
    yum-config-manager --add-repo=http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64 && \
    yum-config-manager --add-repo https://yum.oracle.com/repo/OracleLinux/OL7/olcne13/x86_64/ && \
    yum-config-manager --add-repo https://yum.oracle.com/repo/OracleLinux/OL7/olcne15/x86_64/ && \
    yum-config-manager --add-repo https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64 && \
    yum-config-manager --enable ol7_developer_golang119 && \
    yum install oracle-golang-release-el7 -y && \
    yum clean all

RUN yum update -y && \
    yum install -y bash rh-git227 gcc glibc-static vim less libffi file curl wget ca-certificates unzip tar jq nc mkisofs \
                   openssl-devel libffi-devel python3 iproute vim less bash-completion sysstat acl hostname openssl \
                   helm-3.9.4-1.el7.x86_64 kubectl-1.23.11-1.el7.x86_64 docker-engine-19.03.11.ol-13.el7.x86_64 etcd-3.5.1-2.el7.x86_64 tini-0.19.0-2.el7.x86_64 \
                   golang-1.19 && \

    # Set up needed to ensure git 2.27 from rh-git227 is on the path
    ln /opt/rh/rh-git227/enable /etc/profile.d/git.sh && \
    source /etc/profile.d/git.sh && \
    git version && \
    mv /usr/bin/helm /usr/bin/helm_v3 && \
    go version && \
    yum clean all && \
    rm -rf /var/cache/yum
