ARG RANCHER_BASE_TAG=base
ARG RANCHER_REPO=rancher

FROM ghcr.io/oracle/oraclelinux:7-slim

RUN yum-config-manager --enable ol7_optional_latest && \
    yum-config-manager --enable ol7_addons && \
    yum-config-manager --add-repo=http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64 && \
    yum-config-manager --add-repo https://yum.oracle.com/repo/OracleLinux/OL7/olcne16/x86_64/ && \
    yum-config-manager --add-repo https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64 && \
    yum-config-manager --enable ol7_developer_golang119 && \
    yum install oracle-golang-release-el7 -y && \
    yum update -y && \
    yum install -y git bash gcc glibc-static vim less libffi file curl wget ca-certificates unzip tar jq nc mkisofs \
                   openssl-devel libffi-devel python3 iproute vim less bash-completion sysstat acl hostname openssl \
                   helm-3.11.1-1.el7.x86_64 docker-engine-19.03.11.ol-13.el7.x86_64 etcd-3.5.6-3.el7.x86_64 tini-0.19.0-2.el7.x86_64 \
                   golang-1.19 && \
    mv /usr/bin/helm /usr/bin/helm_v3 && \
    go version && \
    yum clean all && \
    rm -rf /var/cache/yum

ARG DAPPER_HOST_ARCH
ARG CATTLE_DASHBOARD_TAR_URL
ENV CATTLE_DASHBOARD_TAR_URL=$CATTLE_DASHBOARD_TAR_URL
ARG CATTLE_UI_TAR_URL
ENV CATTLE_UI_TAR_URL=$CATTLE_UI_TAR_URL
ARG OCI_OCNE_DRIVER_VERSION
ENV OCI_OCNE_DRIVER_VERSION=$OCI_OCNE_DRIVER_VERSION
ARG OCI_OCNE_DRIVER_HASH
ENV OCI_OCNE_DRIVER_HASH=$OCI_OCNE_DRIVER_HASH
ARG OKE_DRIVER_VERSION
ENV OKE_DRIVER_VERSION=$OKE_DRIVER_VERSION
ARG OKE_DRIVER_HASH
ENV OKE_DRIVER_HASH=$OKE_DRIVER_HASH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}
ENV K3S_ROOT_VERSION v0.11.0
ENV CATTLE_HELM_VERSION v2.16.8-rancher2
ENV CATTLE_MACHINE_VERSION v0.15.0-rancher100
ENV CATTLE_K3S_VERSION v1.26.4+k3s1
# helm 3 version
ENV HELM_VERSION v3.11.3
ENV KUSTOMIZE_VERSION v5.0.1

ENV GOPATH=/go PATH=/go/bin:/usr/local/go/bin:${PATH} SHELL=/bin/bash

# kontainer-driver-metadata branch to be set for specific branch other than dev/master, logic at rancher/rancher/pkg/settings/setting.go
ENV CATTLE_KDM_BRANCH=release-v2.7

ENV KUSTOMIZE_URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_${ARCH}.tar.gz \
    YQ_URL=https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_${ARCH}

RUN curl -sLf ${KUSTOMIZE_URL} | tar -xzf - -C /usr/bin && \
    wget -O - ${YQ_URL} > /usr/bin/yq && chmod +x /usr/bin/yq && \
    chmod +x /usr/bin/kustomize


ENV HELM_HOME /root/.helm
ENV DAPPER_ENV REPO TAG DRONE_TAG DRONE_COMMIT DRONE_BRANCH DRONE_BUILD_EVENT SYSTEM_CHART_DEFAULT_BRANCH FOSSA_API_KEY GOGET_MODULE GOGET_VERSION RELEASE_ACTION RELEASE_TYPE POSTRELEASE_RANCHER_VERSION POSTRELEASE_RANCHER_STABLE
ENV DAPPER_SOURCE /go/src/github.com/rancher/rancher/
ENV DAPPER_OUTPUT ./bin ./dist ./go.mod ./go.sum ./pkg/apis/go.mod ./pkg/apis/go.sum ./pkg/client/go.mod ./pkg/client/go.sum ./scripts/package ./pkg/settings/setting.go ./package/Dockerfile ./Dockerfile.dapper
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_RUN_ARGS "-v rancher2-go16-pkg-1:/go/pkg -v rancher2-go16-cache-1:/root/.cache/go-build --privileged"
ENV GOCACHE /root/.cache/go-build
ENV HOME ${DAPPER_SOURCE}
VOLUME /var/lib/rancher
VOLUME /var/lib/kubelet
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
