FROM ghcr.io/oracle/oraclelinux:8-slim

RUN microdnf update -y --setopt=install_weak_deps=0 --setopt=tsflags=nodocs && \
    microdnf install -y git gcc vim file wget unzip jq nc mkisofs && \
    microdnf install -y glibc-static --enablerepo=ol8_codeready_builder && \
    microdnf install -y openssl-devel libffi-devel python3 iproute bash-completion sysstat hostname && \
    microdnf install -y dnf && \
    microdnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo http://yum.oracle.com/repo/OracleLinux/OL8/olcne17/x86_64 && \
    microdnf install -y helm-3.12.0-3.el8.x86_64 && \
    microdnf install -y kubectl-1.26.10-2.el8.x86_64 && \
    microdnf install -y etcd-3.5.6-4.el8.x86_64 && \
    dnf config-manager --add-repo http://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64 && \
    microdnf install -y tini-0.19.0-1.el8.x86_64 && \
    mv /usr/bin/helm /usr/bin/helm_v3 && \
    microdnf clean all && \
    rm -rf /var/cache/yum /var/lib/rpm/*
