#!/usr/bin/env bash

set -e -x

echo "-- chart/build --"

cd $(dirname $0)/..
. ./version

cd ..
mkdir -p build/chart
rm -rf build/chart/rancher
cp -rf ${1} build/chart/rancher

sed -i -e "s/%VERSION%/${CHART_VERSION}/g" build/chart/rancher/Chart.yaml
sed -i -e "s/%APP_VERSION%/${APP_VERSION}/g" build/chart/rancher/Chart.yaml

CATTLE_SHELL_IMAGE=${CATTLE_SHELL_IMAGE:-"ghcr.io/verrazzano/rancher-shell:v0.1.18-20230403204343-4124528"}
# get the value of shell-image, from env variable set at build time CATTLE_SHELL_IMAGE.
# This value can be overridden at build time by setting the CATTLE_SHELL_IMAGE variable
# The actual value of CATTLE_SHELL_IMAGE will be used at run time by the post delete base.
post_delete_base=$(echo ${CATTLE_SHELL_IMAGE} | cut -d "," -f 2 | sed -e 's/"//g' | sed -e 's/)//g' | sed -e 's/ //g') || ""
post_delete_image_name=$(echo "${post_delete_base}" | cut -d ":" -f 1) || ""
post_delete_image_tag=$(echo "${post_delete_base}" | cut -d ":" -f 2) || ""
if [[ ! ${post_delete_image_name} =~ "ghcr.io/verrazzano/rancher-shell"* ]]; then
  echo "The image name [$post_delete_image_name] is invalid. Its prefix should be ghcr.io/verrazzano/rancher-shell"
  exit 1
fi
if [[ ! ${post_delete_image_tag} =~ ^v.+ ]]; then
  echo "The image tag [$post_delete_image_tag] is invalid. It should start with the letter v"
  exit 1
fi
sed -i -e "s@%POST_DELETE_IMAGE_NAME%@${post_delete_image_name}@g" build/chart/rancher/values.yaml
sed -i -e "s/%POST_DELETE_IMAGE_TAG%/${post_delete_image_tag}/g" build/chart/rancher/values.yaml
