#!/bin/bash

# Copyright (C) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

set -e

cd $(dirname $0)

echo "dapper ci build"
./build
echo "dapper ci package"
./package
echo "dapper ci chart"
./chart/ci
echo "done"
