#!/bin/bash

set -e
source /etc/profile.d/git.sh
git version

source $(dirname $0)/version

source package-env

cd $(dirname $0)/../package

cp ../bin/rancher ../bin/agent ../bin/data.json .
cp ../LICENSE ../README.md ../THIRD_PARTY_LICENSES.txt .

# Make sure the used data.json is a release artifact
cp ../bin/data.json ../bin/rancher-data.json

if [ ${ARCH} == arm64 ]; then
    sed -i -e '$a\' -e 'ENV ETCD_UNSUPPORTED_ARCH=arm64' Dockerfile
fi
if [ ${ARCH} == s390x ]; then
    sed -i -e '$a\' -e 'ENV ETCD_UNSUPPORTED_ARCH=s390x' Dockerfile
fi

echo "The value of CATTLE_DASHBOARD_TAR_URL is ${CATTLE_DASHBOARD_TAR_URL}"
echo "The value of OCI_OCNE_DRIVER_VERSION is ${OCI_OCNE_DRIVER_VERSION}"
echo "The value of OCI_OCNE_DRIVER_VERSION is ${OCI_OCNE_DRIVER_HASH}"

# Compose build args for Rancher Docker image
BUILD_ARGS="--build-arg VERSION=${TAG} --build-arg ARCH=${ARCH} --build-arg IMAGE_REPO=${REPO} --build-arg SYSTEM_CHART_DEFAULT_BRANCH=${SYSTEM_CHART_DEFAULT_BRANCH} --build-arg CHART_DEFAULT_BRANCH=${CHART_DEFAULT_BRANCH}"
if [ -n "${CATTLE_DASHBOARD_TAR_URL}" ]; then
    BUILD_ARGS="${BUILD_ARGS} --build-arg CATTLE_DASHBOARD_TAR_URL=${CATTLE_DASHBOARD_TAR_URL}"
fi
if [ -n "${OCI_OCNE_DRIVER_VERSION}" ]; then
    BUILD_ARGS="${BUILD_ARGS} --build-arg OCI_OCNE_DRIVER_VERSION=${OCI_OCNE_DRIVER_VERSION}"
fi
if [ -n "${OCI_OCNE_DRIVER_HASH}" ]; then
  BUILD_ARGS="${BUILD_ARGS} --build-arg OCI_OCNE_DRIVER_HASH=${OCI_OCNE_DRIVER_HASH}"
fi

docker build $BUILD_ARGS -t ${IMAGE} .

docker build --build-arg VERSION=${TAG} --build-arg ARCH=${ARCH} --build-arg RANCHER_TAG=${TAG} --build-arg RANCHER_REPO=${REPO} -t ${AGENT_IMAGE} -f Dockerfile.agent .

mkdir -p ../dist
echo ${IMAGE} > ../dist/images
echo ${AGENT_IMAGE} >> ../dist/images
echo Built ${IMAGE} #${AGENT_IMAGE}
echo

cd ../bin


if [ ! -d $CHART_REPO_DIR ]; then
    git clone --branch $CHART_DEFAULT_BRANCH https://github.com/rancher/charts $CHART_REPO_DIR
fi

if [ ${ARCH} == amd64 ]; then
    # Move this out of ARCH check for local dev on non-amd64 hardware.
    TAG=$TAG REPO=${REPO} go run ../pkg/image/export/main.go $CHART_REPO_DIR $IMAGE $AGENT_IMAGE
fi

# Create components file used for pre-release notes
../scripts/create-components-file.sh
