ARG RANCHER_BASE_TAG=base
ARG RANCHER_BASE_REPO=rancher

FROM ghcr.io/oracle/oraclelinux:8-slim as build
ARG ARCH
ENV ARCH=$ARCH

COPY . /go/src/github.com/rancher/rancher/

RUN microdnf update -y --setopt=install_weak_deps=0 --setopt=tsflags=nodocs && \
    microdnf install -y git && \
    microdnf install -y golang-1.20.10-1.module+el8.9.0+90068+08775a1f.x86_64 && \
    cd /go/src/github.com/rancher/rancher/scripts && \
    ./build

# Use the build of Dockerfile.base as the FROM image
FROM ${RANCHER_BASE_REPO}/rancher:${RANCHER_BASE_TAG}

ARG ARCH=amd64

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV LOGLEVEL_VERSION v0.1.5

RUN curl -sLf https://github.com/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz | tar xvzf - -C /usr/bin

ARG VERSION=dev
LABEL io.cattle.agent true
ENV AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV CATTLE_RANCHER_WEBHOOK_MIN_VERSION=''
# For now, this value needs to be manually synced with the one in the main Dockerfile. This pins downstream webhook's version.
ENV CATTLE_RANCHER_WEBHOOK_VERSION=2.0.5+up0.3.5
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs

COPY agent run.sh kubectl-shell.sh shell-setup.sh /usr/bin/
COPY --from=build /var/lib/rancher-data /var/lib/rancher-data
COPY --from=build /usr/bin/tini /usr/bin/
RUN mkdir /license
COPY ${HOME}/LICENSE ${HOME}/README.md ${HOME}/THIRD_PARTY_LICENSES.txt /license/
WORKDIR /var/lib/rancher
ENTRYPOINT ["run.sh"]
