ARG RANCHER_BASE_TAG=base
ARG RANCHER_BASE_REPO=rancher
ARG RANCHER_TAG=dev
ARG RANCHER_REPO=rancher
# Use the build of Dockerfile to obtain some build outputs
FROM ${RANCHER_REPO}/rancher:${RANCHER_TAG} as rancher

ARG ARCH=amd64

FROM ghcr.io/verrazzano/golang:v1.20.12 as build
ARG ARCH
ENV ARCH=$ARCH

COPY . /go/src/github.com/rancher/rancher/

RUN dnf config-manager --enable ol8_appstream && \
    dnf install -y git && \
    cd /go/src/github.com/rancher/rancher/scripts && \
    ./build

# Use the build of Dockerfile.base as the FROM image
FROM ${RANCHER_BASE_REPO}/rancher:${RANCHER_BASE_TAG}

ARG ARCH=amd64

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV LOGLEVEL_VERSION v0.1.5

RUN curl -sLf https://github.com/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz | tar xvzf - -C /usr/bin

ARG VERSION=dev
LABEL io.cattle.agent true
ENV AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV CATTLE_RANCHER_WEBHOOK_MIN_VERSION=''
# For now, this value needs to be manually synced with the one in the main Dockerfile. This pins downstream webhook's version.
ENV CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs

COPY --from=build /go/src/github.com/rancher/rancher/bin/agent /usr/bin/
COPY --from=build /go/src/github.com/rancher/rancher/package/run.sh /usr/bin/
COPY --from=build /go/src/github.com/rancher/rancher/package/kubectl-shell.sh /usr/bin/
COPY --from=build /go/src/github.com/rancher/rancher/package/shell-setup.sh /usr/bin/
COPY --from=rancher /var/lib/rancher-data /var/lib/rancher-data
RUN mkdir /license
COPY --from=build /go/src/github.com/rancher/rancher/LICENSE /license/
COPY --from=build /go/src/github.com/rancher/rancher/README.md /license/
COPY --from=build /go/src/github.com/rancher/rancher/THIRD_PARTY_LICENSES.txt /license/
WORKDIR /var/lib/rancher
ENTRYPOINT ["run.sh"]
